package com.sim.spriced.framework.models;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Table;

import com.sim.spriced.framework.annotations.ExtraColumnData;
import com.sim.spriced.framework.annotations.IDType;
import com.sim.spriced.framework.constants.ModelConstants;
import com.sim.spriced.framework.models.AttributeConstants.ConstraintType;
import com.sim.spriced.framework.models.AttributeConstants.DataType;
import com.sim.spriced.framework.models.AttributeConstants.Type;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@Table(name = "entity")
public class EntityDefnition extends BaseEntity {

	private static final int NAME_SIZE = 25;
	private static final String CODE = "code";
	private static final String ID = "id";

	@ExtraColumnData(isPrimaryKey = true,id = IDType.AUTO)
	@Column(name = ModelConstants.ID)
	private Integer id;
	
	@Column(name = ModelConstants.NAME)
	private String name;
	
	@Column(name = ModelConstants.DISPLAY_NAME)
	private String displayName;

	@Column(name = "group_id")
	private Integer groupId;

	@Column(name = ModelConstants.IS_DISABLED)
	private Boolean isDisabled;
	
	@Column(name = ModelConstants.ENABLE_AUDIT_TRIAL)
	private Boolean enableAuditTrial;

	
	@Column(name = "comment")
	private String comment;
	
	@Column(name = ModelConstants.ATTRIBUTES)
	@ExtraColumnData(convertToJson = true, exclude = true)
	private final List<Attribute> attributes = new ArrayList<>();

	@Column(name = ModelConstants.AUTO_NUMBER)
	@ExtraColumnData(exclude = true)
	private Boolean autoNumberCode = true;
	
	public EntityDefnition(int id) {
		this.id = id;
	}
	
	public EntityDefnition(String name) {
		this.name = name;
	}
	
	public EntityDefnition(String name,int groupId) {
		this.name = name;
		this.groupId = groupId;
	}

	public EntityDefnition(String name, boolean isDisabled) {
		this.name = name;
		this.isDisabled = isDisabled;
	}
	
	public void addAttributes(List<Attribute> attributes) {
		this.attributes.addAll(attributes);
	}

	@Override
	public boolean validate() {
		this.validateDisplayName();
		this.validateAttributes();
		return true;
	}

	private void validateDisplayName() {
		if(this.displayName==null) {
			this.displayName = this.name;
		}
	}
	
	
	private void validateAttributes() {
		int nameCount = 0;
		int primaryKeyCount = 0;
		int codeCount = 0;
		boolean isValidPresent = false;
		boolean updatedDatePresent = false;
		boolean updatedByPresent = false;
		boolean commentPresent = false;
		//boolean errorPresent = false;
		
		for (var attr : this.attributes) {
			
			attr.setName(attr.getName().toLowerCase());
			if(attr.getConstraintType() == ConstraintType.PRIMARY_KEY) {
				primaryKeyCount = primaryKeyCount + 1;
			}
			
			if(attr.getConstraintType()==ConstraintType.PRIMARY_KEY || attr.getConstraintType()==ConstraintType.FOREIGN_KEY || attr.getDataType()==DataType.BUSINESS_SEQUENCE) {
				attr.setNullable(false);
			}
			
			if (attr.getName().equals(ModelConstants.NAME)) {
				nameCount = nameCount + 1;
			}
			else if (attr.getName().equals(ModelConstants.IS_VALID)) {
				isValidPresent = true;
				attr.setEditable(false);
				attr.setShowInForm(false);
			}
			else if (attr.getName().equals(ModelConstants.UPDATED_BY)) {
				attr.setEditable(false);
				attr.setShowInForm(false);
				updatedByPresent = true;
			}
			else if (attr.getName().equals(ModelConstants.UPDATED_DATE)) {
				attr.setEditable(false);
				attr.setShowInForm(false);
				updatedDatePresent = true;
			}
			else if (attr.getName().equals(ModelConstants.COMMENT)) {
				attr.setEditable(true);
				commentPresent = true;
			} else if (attr.getName().equals(CODE)) {
				codeCount = codeCount + 1;
			}
//			else if (attr.getName().equals(ModelConstants.ERROR)) {
//				attr.setEditable(false);
//				commentPresent = true;
//			}
			
		}
		
		if(primaryKeyCount==0) {
			Attribute codeAttr = new Attribute(ID,Type.FREE_FORM,DataType.AUTO);
			
			codeAttr.setEditable(false);
			codeAttr.setShowInForm(false);
			codeAttr.setAutoGenerated(true);
			codeAttr.setConstraintType(ConstraintType.PRIMARY_KEY);
			codeAttr.setNullable(false);
			this.attributes.add(0,codeAttr);
		}
		
		if(nameCount==0) {
			Attribute nameAttr = new Attribute(ModelConstants.NAME,Type.FREE_FORM,DataType.STRING_VAR , NAME_SIZE);
			nameAttr.setConstraintType(ConstraintType.UNIQUE_KEY);
			nameAttr.setNullable(false);
			nameAttr.setAutoGenerated(true);
			nameAttr.setEditable(true);
			this.attributes.add(1,nameAttr);
		}
		
		if(!isValidPresent) {
			Attribute isValidAttr = new Attribute(ModelConstants.IS_VALID,Type.FREE_FORM,DataType.BOOLEAN);
			isValidAttr.setDefaultValue(true);
			isValidAttr.setAutoGenerated(true);
			isValidAttr.setEditable(false);
			isValidAttr.setNullable(true);
			isValidAttr.setShowInForm(false);
			this.attributes.add(isValidAttr);
		}
		
		if(!updatedDatePresent) {
			Attribute updatedDateAttr = new Attribute(ModelConstants.UPDATED_DATE,Type.FREE_FORM,DataType.TIME_STAMP);
			updatedDateAttr.setAutoGenerated(true);
			updatedDateAttr.setEditable(false);
			updatedDateAttr.setShowInForm(false);
			this.attributes.add(updatedDateAttr);
		}
		
		if(!updatedByPresent) {
			Attribute updatedByAttr = new Attribute(ModelConstants.UPDATED_BY,Type.FREE_FORM,DataType.STRING_VAR,50);
			updatedByAttr.setAutoGenerated(true);
			updatedByAttr.setEditable(false);
			this.attributes.add(updatedByAttr);
		}
		
		if(!commentPresent) {
			Attribute commentAttr = new Attribute(ModelConstants.COMMENT,Type.FREE_FORM,DataType.STRING_VAR,250);
			commentAttr.setAutoGenerated(true);
			commentAttr.setEditable(true);
			this.attributes.add(commentAttr);
		}

		if(codeCount==0){
			Attribute codeAttribute = new Attribute(CODE,Type.FREE_FORM,DataType.INTEGER,NAME_SIZE);
			if(!this.getAutoNumberCode()) {
				codeAttribute.setDataType(DataType.STRING_VAR);
				codeAttribute.setSize(50);
				codeAttribute.setEditable(true);
			}
			codeAttribute.setConstraintType(ConstraintType.UNIQUE_KEY);
			codeAttribute.setNullable(false);
			codeAttribute.setEditable(true);
			codeAttribute.setShowInForm(false);
			this.attributes.add(2,codeAttribute);
		}
		
//		if(!errorPresent) {
//			Attribute errorAttr = new Attribute(ModelConstants.ERROR,Type.FREE_FORM,DataType.JSON);
//			errorAttr.setAutoGenerated(true);
//			errorAttr.setEditable(true);
//			errorAttr.setSystemAttribute(true);
//			this.attributes.add(errorAttr);
//		}
		
	}

}
