export interface modelData {
    id: number;
    name: string;
    displayName: string;
    isDisabled: boolean;
    updatedDate: string;
    updatedBy: string;
}

interface Condition {
    conditionType: string;
    attributeId: string;
    operatorType: string;
    operandType: string;
    operand?: string;
}

interface Action {
    attributeId: string;
    actionGroup: string;
    actionType: string;
    operand?: string;
}

interface ConditionalAction {
    ifActions: Action[];
    elseActions: Action[];
}

interface Attribute {
    id: string,
    name: string,
    dataType: string,
    type: string,
    size: number,
    nullable: boolean,
    numberOfDecimalValues: number,
    constraintType: string,
    editable: boolean,
    autoGenerated: boolean,
    systemAttribute: boolean
}

export interface Entity {
    id: number,
    name: string,
    displayName: string,
    groupId: number,
    isDisabled: boolean,
    enableAuditTrial: boolean,
    comment: string,
    attributes: Attribute[],
    autoNumberCode: boolean,
    updatedDate: string,
    updatedBy: string
}

export interface Rule {
    id: number;
    entityId: number;
    priority: number;
    name: boolean;
    description: string;
    isExcluded: boolean;
    status: string;
    notification: string;
    group: string;
    condition: Condition[];
    conditionalAction: ConditionalAction;
    updatedDate: string;
    updatedBy: string;
}

export interface conditionTypes {
    AND: string;
    NONE: string;
    NOT: string;
    OR: string;
}

export interface operandType {
    ATTRIBUTE: string;
    BLANK: string;
    CONSTANT: string;
}
export interface operatorType {
    CONTAINS_PATTERN: string;
    CONTAINS_SUBSET: string;
    DOES_NOT_CONTAIN_PATTERN: string;
    DOES_NOT_CONTAIN_SUBSET: string;
    DOES_NOT_END_WITH: string;
    DOES_NOT_START_WITH: string;
    ENDS_WITH: string;
    EQUALS: string;
    GREATER_THAN: string;
    GREATER_THAN_EQUALS: string;
    HAS_CHANGED: string;
    HAS_NOT_CHANGED: string;
    IS_BETWEEN: string;
    IS_NOT_BETWEEN: string;
    IS_NOT_EQUAL: string;
    LESS_THAN: string;
    LESS_THAN_EQUALS: string;
    NONE: string;
    STARTS_WITH: string;
}
export interface dataTypes {
    AUTO: string
    BIT: string
    BOOLEAN: string
    BUSINESS_SEQUENCE: string
    CHARACTER: string
    DATE: string
    DATE_TIME: string
    DECIMAL: string
    DOUBLE: string
    FLOAT: string
    INTEGER: string
    JSON: string
    LINK: string
    STRING: string
    STRING_VAR: string
    TEXT: string
    TIME_STAMP: string
    XML: string
}
